import { HR } from '@/types';

export const sampleHRs: Omit<HR, 'id'>[] = [
  {
    name: 'Ayesha Malik',
    photo: 'https://randomuser.me/api/portraits/women/44.jpg',
    company: 'Systems Limited',
    position: 'Senior HR Manager',
    experience: 9,
    skills: ['Talent Acquisition', 'Behavioral Interviewing', 'Campus Recruitment', 'Onboarding'],
    bio: 'Ayesha has over 9 years of experience in HR, specializing in technology sector recruitment. She has helped 300+ fresh graduates land their first jobs and is passionate about bridging the gap between academia and industry.',
    education: 'MBA (HRM) – IBA Karachi',
    languages: ['English', 'Urdu'],
    interview_domains: ['Software Engineering', 'Data Science', 'Business Analysis', 'Product Management'],
    availability: 'Mon–Fri, 10am–4pm PKT',
  },
  {
    name: 'Usman Tariq',
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
    company: 'Netsol Technologies',
    position: 'Head of Talent',
    experience: 12,
    skills: ['Technical Interviews', 'Leadership Assessment', 'Culture Fit', 'Employer Branding'],
    bio: 'Usman leads talent acquisition at Netsol Technologies and has personally interviewed over 1000 candidates. He specializes in technical roles and loves helping engineers prepare for whiteboard-style interviews.',
    education: 'BS Computer Science – FAST-NUCES',
    languages: ['English', 'Urdu', 'Punjabi'],
    interview_domains: ['Software Engineering', 'DevOps', 'Cloud Computing', 'Cybersecurity'],
    availability: 'Tue & Thu, 2pm–6pm PKT',
  },
  {
    name: 'Sana Rizvi',
    photo: 'https://randomuser.me/api/portraits/women/68.jpg',
    company: 'Telenor Pakistan',
    position: 'HR Business Partner',
    experience: 7,
    skills: ['Career Counseling', 'Competency Mapping', 'Graduate Programs', 'Interview Coaching'],
    bio: 'Sana is an HRBP at Telenor with deep expertise in graduate hiring programs. She regularly mentors students through structured interview preparation and career path planning sessions.',
    education: 'MS HRM – LUMS',
    languages: ['English', 'Urdu'],
    interview_domains: ['Marketing', 'Finance', 'Human Resources', 'Operations'],
    availability: 'Wed & Fri, 11am–3pm PKT',
  },
  {
    name: 'Bilal Chaudhry',
    photo: 'https://randomuser.me/api/portraits/men/75.jpg',
    company: 'Arbisoft',
    position: 'Engineering Recruiter',
    experience: 5,
    skills: ['Technical Screening', 'React', 'Node.js', 'System Design'],
    bio: 'Bilal focuses on engineering recruitment at Arbisoft, one of Pakistan\'s top software companies. He offers mock technical interviews including coding challenges and system design discussions for aspiring engineers.',
    education: 'BS Software Engineering – UET Lahore',
    languages: ['English', 'Urdu'],
    interview_domains: ['Frontend Development', 'Backend Development', 'Full Stack', 'Mobile Development'],
    availability: 'Mon, Wed, Fri, 5pm–8pm PKT',
  },
  {
    name: 'Fatima Zahra',
    photo: 'https://randomuser.me/api/portraits/women/26.jpg',
    company: 'HBL',
    position: 'Talent Acquisition Lead',
    experience: 10,
    skills: ['Banking Interviews', 'Case Interviews', 'Psychometric Testing', 'Group Discussions'],
    bio: 'Fatima leads graduate hiring at HBL and has an exceptional track record of preparing candidates for structured banking and finance interviews. She is well-versed in HBL\'s Management Trainee Officer program.',
    education: 'MBA Finance – SZABIST',
    languages: ['English', 'Urdu', 'Sindhi'],
    interview_domains: ['Banking', 'Finance', 'Accounting', 'Investment'],
    availability: 'Sat, 10am–2pm PKT',
  },
  {
    name: 'Omar Sheikh',
    photo: 'https://randomuser.me/api/portraits/men/54.jpg',
    company: 'Unilever Pakistan',
    position: 'Senior Recruiter',
    experience: 8,
    skills: ['Case Studies', 'FMCG Interviews', 'Leadership Competencies', 'Assessment Centers'],
    bio: 'Omar recruits top talent for Unilever Pakistan and has conducted 500+ interviews for FMCG roles. He specializes in preparing candidates for competency-based interviews and structured assessment centers.',
    education: 'BBA Marketing – IBA Karachi',
    languages: ['English', 'Urdu'],
    interview_domains: ['Marketing', 'Supply Chain', 'Sales', 'General Management'],
    availability: 'Mon–Wed, 6pm–9pm PKT',
  },
];
